### ISSUE TITLE
Suggested optimization: use IntoIterator and Cell

### ISSUE THREAD

**Issue by Kixunil** [SOF3/serde-iter#1]
It'd be nice to use `IntoIterator + Clone` instead of `Iterator + Clone` in `serialize` functions. This is backwards compatible because `Iterator` implies `IntoIterator`. This would allow for the following optimization:

* use `Cell` inside `CloneOnce`
* The implementation of `Clone` would reduce to calling `take()` on the cell and wrapping the result, no funny borrowing
* impl `IntoIterator<Iter=T>` instead of `Iterator` - this is formally backwards incompatible, but only breaks user code if the user iterates on it directly (using `.next()` method or combinators, passing it into `for` would still work for instance), this would avoid the cost of calling borrow on each call to `next()`

To resolve the last point, I'd suggest to release version `0.2` and a semver trick version `0.1.2` that has the old implementation of `CloneOnce` with `From` implemented both ways. Maybe with a deprecation message to warn the users.

**Comment by SOF3** [comment]
> Use `Cell` inside `CloneOnce`

Oh nice, I didn't know to use `Cell<Option<T>>` with `take()`.

> Change `Iterator` to `IntoIterator`

How is that related to using `Cell`?

**Comment by Kixunil** [comment]
Without changing `Iterator` to `IntoIterator`, you'd have to `take()` the cell and put it back every time `next()` is called. Using `IntoIterator`, you can take it out once, before the iteration begins.

**Comment by SOF3** [comment]
Can you illustrate this with a pull request? I changed RefCell to Cell on a branch. You can try basing on that branch.

**Comment by Kixunil** [comment]
Sure!

**Comment by Kixunil** [comment]
Done. :)
